config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  authenticate :user do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    root 'home#index'
    resources :contracts, only: %i[index]
    resources :tasks, only: %i[index]

    resources :reports, only: %i[index]
    get '/reports/reports/new' => 'reports#new', as: :new_report
    post '/reports/reports' => 'reports#create', as: :create_report
    post 'reports/export_xls' => 'reports#export_xls', as: :export_report_as_xls

    post 'dashboard/update_dashboard' => 'home#update_dashboard', as: :update_dashboard
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dashboard = generate_dashboard_presenter(@current_date_info)
  end

  def update_dashboard
    dashboard_presenter = generate_dashboard_presenter(@current_date_info)
    message = generate_message_for_current_dashboard_context(dashboard_presenter)
    charts_objects = generate_charts_objects(dashboard_presenter)
    broadcast_dashboard_update(dashboard_presenter, message, charts_objects)
    head :ok
  end

  private

  def generate_dashboard_presenter(date_info)
    contracts = ContractService.get_contracts_from_company_filtered_by_month_and_year(current_user.company_id, date_info[:month], date_info[:year])
    contract_id = params[:contract]
    selected_contracts = DashboardService.update_selected_contracts(contracts, contract_id)
    return DashboardPresenter.new(contracts, date_info, selected_contracts, contract_id) if contract_id.present?
    DashboardPresenter.new(contracts, date_info, selected_contracts)
  end

  def generate_message_for_current_dashboard_context(dashboard_presenter)
    contract_id = dashboard_presenter.selected_contract
    selected_contracts = dashboard_presenter.selected_contracts
    DashboardService.create_dashboard_message(contract_id, selected_contracts)
  end

  def generate_charts_objects(dashboard)
    {
      pie_chart_contracts: DashboardService.generate_contracts_object_for_chart(dashboard.contracts),
      bar_chart_contracts: DashboardService.generate_contracts_object_for_bar_chart(dashboard, current_user.company_id)
    }
  end

  def broadcast_dashboard_update(dashboard_presenter, message, charts_objects)
    broadcast_object = DashboardService.generate_broadcast_object(dashboard_presenter, message, charts_objects)
    ActionCable.server.broadcast "dashboard_#{current_user.id}", broadcast_object
  end
end

app/views/home/_charts.html.erb
<% if dashboard.selected_contracts.size > 1 %>
  <div class="col-lg-3">
    <%= render partial: '/home/charts/pie_chart', locals: { title: t('.pie_chart_title'), chart_id: 'flot-pie-chart' } %>
  </div>
  <div class="col-lg-9">
    <%= render partial: '/home/charts/bar_chart', locals: { title: t('.bar_chart_title', year: dashboard.dashboard_year) } %>
  </div>
<% else %>
  <div class="col-lg-12">
    <%= render partial: '/home/charts/bar_chart', locals: { title: t('.bar_chart_title', year: dashboard.dashboard_year) } %>
  </div>
<% end %>

app/views/home/_dashboard_notification.html.erb
<div id="dashboard-notification">
  <div class='alert alert-info'>
    <div class="message">
      <%= message %>
      <i class="fa fa-smile-o"></i>
    </div>
    <%= render '/shared/loading/loading' %>
  </div>
</div>

app/views/home/_filter_contracts.html.erb
<%= simple_form_for('', remote: true, url: update_dashboard_path, html: { id: 'filter_contracts_form' }) do |f| %>
  <div class='form-filter-contracts-item contract'>
    <%= f.input :contract, label: false, collection: dashboard.contracts_for_filter, selected: dashboard.selected_contract,
          input_html: { id: "filtered_contract" } %>
  </div>
<% end %>

app/views/home/_panel_primary.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-3">
        <i class="fa fa-tasks fa-5x"></i>
      </div>
      <div class="col-xs-9 text-right">
        <div class="huge"><%= number %></div>
        <div><%= text %></div>
      </div>
    </div>
  </div>
  <%= link_to(details_url) do %>
    <div class="panel-footer">
      <span class="pull-left">View Details</span>
      <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
      <div class="clearfix"></div>
    </div>
  <% end %>
</div>

app/views/home/_panel_secondary.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-3">
          <i class="fa fa-clock-o fa-5x"></i>
      </div>
      <div class="col-xs-9 text-right">
          <div class="huge"><%= number %></div>
          <div><%= text %></div>
      </div>
    </div>
  </div>
  <%= link_to(details_url) do %>
    <div class="panel-footer">
      <span class="pull-left">View Details</span>
      <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
      <div class="clearfix"></div>
    </div>
  <% end %>
</div>

app/views/home/_remaining_hours_panel.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-3">
          <i class="fa fa-clock-o fa-5x"></i>
      </div>
      <div class="col-xs-9 text-right">
          <div class="huge"><%= dashboard.number_remaining_hours %></div>
          <div><%= text %></div>
      </div>
    </div>
  </div>
  <div class="panel-footer left-hours">
    <%= render "home/remaining_hours/#{dashboard.remaining_hours_message_partial_name}" %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/home/index.html.erb
<div id="dashboard_container">
  <div class="row">
    <div id="section_notification" class="col-lg-10 col-md-2"></div>
    <div id="section_filter_contracts" class="col-lg-2 col-md-2">
      <%= render partial: '/home/filter_contracts', locals: { dashboard: @dashboard } %>
    </div>
  </div>

  <div class="row">
    <div id="section_number_plans" class="col-lg-3 col-md-6"></div>
    <div id="section_number_hired_hours" class="col-lg-3 col-md-6"></div>
    <div id="section_number_consumed_hours" class="col-lg-3 col-md-6"></div>
    <div id="section_number_remaining_hours" class="col-lg-3 col-md-6"></div>
  </div>

  <div class="row">
    <div id="charts"></div>
  </div>
</div>