config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  authenticate :user do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    root 'home#index'
    resources :contracts, only: %i[index]
    resources :tasks, only: %i[index]

    resources :reports, only: %i[index]
    get '/reports/reports/new' => 'reports#new', as: :new_report
    post '/reports/reports' => 'reports#create', as: :create_report
    post 'reports/export_xls' => 'reports#export_xls', as: :export_report_as_xls

    post 'dashboard/update_dashboard' => 'home#update_dashboard', as: :update_dashboard
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @report = Objects::ReportObject.new
  end

  def create
    @locals = generate_report_data
    respond_to do |format|
      format.js
    end
  end

  def export_xls
    @locals = generate_report_data
    filename = "report_#{DateTime.now.to_s(:date_format)}"
    render xlsx: filename, template: 'reports/export_xls.xlsx.axlsx'
  end

  private

  def generate_report_data
    date_info = date_params
    contracts = get_contracts(date_info)
    create_response_object(date_info, contracts)
  end

  def get_contracts(date_info)
    ReportService.get_contracts_for_date_range(date_info[:start_date], date_info[:end_date], current_user)
  end

  def create_response_object(date_info, contracts)
    summed_hours = ReportService.sum_contracts_hours(contracts)
    { start_date: date_info[:start_date], end_date: date_info[:end_date], contracts: contracts, contract_summed_hours: summed_hours }
  end

  def report_params
    params.require(:objects_report_object).permit(:start_date, :end_date, :submit)
  end

  def date_params
    { start_date: report_params[:start_date].to_date, end_date: report_params[:end_date].to_date }
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def human_readable_time(month_year)
    args = qualify_params(month_year)
    readable_month = map_month_to_human_readable(args[:month])
    "#{readable_month}/#{args[:year]}"
  end

  def contract_plan_name(plan)
    plan.name
  end

  private

  def qualify_params(raw_params)
    args = raw_params.split('_')
    { month: args.first.to_i, year: args.last.to_i }
  end

  def map_month_to_human_readable(month)
    Date::MONTHNAMES[month]
  end
end

app/views/reports/_report.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="col-lg-1 col-md-1"></div>
    <div class="col-lg-10 col-md-10">
      <div class="col-lg-2 col-md-6"></div>
      <div class="col-lg-4 col-md-6">
        <%= simple_form_for(report, url: create_report_path, remote: true, html: { id: 'report_form' }) do |f| %>
          <%= render 'report_filters', f: f %>
        <% end %>
        <%= simple_form_for(report, url: export_report_as_xls_path, method: :xlsx, html: { id: 'report_export_form' }) do |f| %>
          <%= render 'report_filters', f: f %>
        <% end %>
      </div>
      <div class="col-lg-3 col-md-6">
        <%= render 'report_actions' %>
      </div>
      <div class="col-lg-3 col-md-6"></div>
    </div>
    <div class="col-lg-1 col-md-1"></div>
  </div>
</div>

app/views/reports/_report_actions.html.erb
<div class="panel panel-default">
  <div class="panel-heading" style="text-align: center;">
    <%= t('.title') %>
  </div>
  <div class="panel-body">
    <div class="col-lg-12 col-md-6 report-actions">
      <div class="actions">
        <div id="action_generate_report" class="actions-items">
          <%= link_to t('.buttons.generate'), '', id: 'generate_report_btn', class: 'btn btn-default submit' %>
        </div>

        <div id="action_export_csv" class="actions-items">
          <%= link_to t('.buttons.export'), '', id: 'export_as_xls_btn', disabled: true, class: 'btn btn-default' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_report_filters.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('.title') %>
  </div>
  <div class="panel-body">
    <div class="col-lg-12 col-md-6 report-filters">
      <div class="report-filters-container filters-date-from">
        <%= f.input :start_date, hint: false,
              input_html: { id: "#{f.options[:html][:id]}_start_date", class: 'datepicker',
              data: { date_options: { defaultDate: Date.today.beginning_of_month } } }
        %>
      </div>
      <div class="report-filters-container filters-date-to">
        <%= f.input :end_date, hint: false,
              input_html: { id: "#{f.options[:html][:id]}_end_date", class: 'datepicker',
              data: { date_options: { defaultDate: Date.today.end_of_month } } }
        %>
      </div>
    </div>
  </div>
</div>

app/views/reports/_report_results.html.erb
<div class="row">
  <div class="col-lg-12" id="period_details">
    <div class="panel panel-default">
      <div class="panel-heading">
        <span>
          <%= t('.period_title') %>
        </span> <%= "#{start_date.to_s(:date_format)} - #{end_date.to_s(:date_format)}"  %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12" id="summary_hiring">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-file-text"></i> <%= t('.summary_title') %>
      </div>
      <div class="panel-body">
        <%= render partial: 'reports/results/summary', locals: { contracts: contracts, contract_summed_hours: contract_summed_hours } %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12" id="detailed_hiring">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-file-text"></i> <%= t('.details_title') %>
      </div>
      <div class="panel-body">
        <%= render partial: 'reports/results/details', locals: { contracts: contracts } %>
      </div>
    </div>
  </div>
</div>

app/views/reports/create.js.erb
$('#report-data-container').html("<%= j render(partial: 'report_results', locals: @locals) %>")
$('#export_as_xls_btn').removeAttr('disabled')

app/views/reports/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header"><%= t('.title') %></h2>
  </div>
</div>

<div id="report-container">
  <%= render 'report', report: @report %>
</div>

<div id="report-data-container"></div>